name: liferay-workspace-testing
services:
    liferay:
        container_name: lrws-testing-liferay-portal
        healthcheck:
            interval: 5s
            timeout: 5m
            test: test -d /opt/liferay/routes/default/liferay-sample-etc-node && test -d /opt/liferay/routes/default/liferay-sample-etc-spring-boot && curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/web/guest | grep 200 &>/dev/null
        image: liferay-workspace-testing-liferay:7.4.3.125-ga125
        ports:
            - "8080:8080"
#            - "8000:8000"
#            - "11311:11311"
        volumes:
            - routes_dir:/opt/liferay/routes
    microservice-node:
        container_name: lrws-testing-microservices-node
        depends_on:
            liferay:
                condition: service_healthy
        env_file: microservice_node.env
        image: liferay-sample-etc-node:latest
        ports:
            - "3001:3001"
        restart: 'on-failure'
        volumes:
            - routes_dir:/etc/liferay/routes
    microservice-spring-boot:
        container_name: lrws-testing-microservices-spring-boot
        depends_on:
            liferay:
                condition: service_healthy
        env_file: microservice_spring_boot.env
        image: liferay-sample-etc-spring-boot:latest
        ports:
            - "58081:58081"
        restart: 'on-failure'
        volumes:
            - routes_dir:/etc/liferay/routes
volumes:
    routes_dir: